# Generated by Django 3.1.6 on 2021-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210223_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonUser', models.CharField(max_length=50)),
                ('anonComment', models.TextField(blank=True, max_length=140)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
