# Generated by Django 3.1.6 on 2021-02-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_anoncomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonComment',
        ),
    ]
