# Generated by Django 3.1.6 on 2021-03-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.DateField(auto_now=True)),
                ('to_year', models.DateField(auto_now=True)),
                ('position_held', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
