# Generated by Django 3.1.6 on 2021-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210310_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='from_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='to_year',
            field=models.DateField(),
        ),
    ]
