# Generated by Django 3.1.6 on 2021-03-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210310_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site_url', models.CharField(max_length=299)),
            ],
        ),
        migrations.AddField(
            model_name='workexp',
            name='site_urls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='siteurls', to='blog.jsonfieldmodel'),
            preserve_default=False,
        ),
    ]
