# Generated by Django 3.1.6 on 2021-03-13 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210312_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexp',
            name='site_urls',
        ),
        migrations.AddField(
            model_name='jsonfieldmodel',
            name='workexp_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workexp_urls', to='blog.workexp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jsonfieldmodel',
            name='site_url',
            field=models.URLField(),
        ),
    ]
