# Generated by Django 3.1.6 on 2021-03-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210313_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonFieldModel',
        ),
    ]
