# Generated by Django 3.1.6 on 2021-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_jsonfieldmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_img', models.ImageField(upload_to='project_images/')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('tech_used', models.TextField()),
                ('project_url', models.URLField()),
                ('github_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
