# Generated by Django 3.1.6 on 2021-03-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_projectmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
