# Generated by Django 3.1.6 on 2021-03-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_img',
        ),
    ]
