# Generated by Django 3.1.6 on 2021-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default=1, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
